### ISSUE TITLE
Log-likelihood doubt

### ISSUE THREAD

**Issue by Valerio-Colombo** [LucasAlegre/mbcd#2]
Hi,
I have some doubts on the likelihood estimation performed by the function `def get_logprob2(self, x, means, variances):` at line 77 in `mbcd.py` file.
From the comment at line 76 the variable `log_prob` should have `[num_networks, batch_size]` size but the result of line 77 is a scalar. The following lines(80) assume that the result is a matrix,
```
76    ## [ num_networks, batch_size ]
77    log_prob = -1/2 * (k*np.log(2*np.pi) + np.log(variance).sum(-1) + (np.power(x-mean, 2)/variance).sum(-1))  # [1,]
78
79    ## [ batch_size ]
80    prob = np.exp(log_prob).sum(axis=0)
81
82    ## [ batch_size ]
83    log_prob = np.log(prob + 1e-8)  # Avoid log of zero
```
Is that a problem?

Furthermore, I want to ask you some clarification about the `var_mean` formulas at line 85 and 86. 
In the code there are two formulas which leads to different results. 
```
85    var_mean = np.var(means, axis=0).max(axis=-1)
86    var_mean = np.linalg.norm(np.std(means, axis=0), axis=-1)
```
Which of the two is the right one to use?
Thank you in advance

**Comment by LucasAlegre** [comment]
Hi,

Sorry for the confusion, these comments came from the method `_get_log_prob` of file models/fake_env.py, which operates over batches of transitions.
This `get_logprob2` method operates over only the current experience transition (batch_size = 1), so it is correct that the outputs are scalars. Ps: the .sum(axis=0) in line 80 is actually doing nothing here.

Regarding `var_mean`, these are different uncertainty estimation methods. The one used in the paper is the uncommented one.
`var_mean = np.linalg.norm(np.std(means, axis=0), axis=-1)`
This is computing the standard deviation of the ensemble predicitions (i.e. how different/disagreeing are the predictions of each ensemble member) over each state dimension, and then computind the norm of this vector.

**Comment by Valerio-Colombo** [comment]
Thank you very very much for the answer
