### ISSUE TITLE
Doubt on rollout length calculation

### ISSUE THREAD

**Issue by Valerio-Colombo** [LucasAlegre/mbcd#4]
Hi,
I have a doubt about the following method.
https://github.com/LucasAlegre/mbcd/blob/4be85b964bf02818f2fc83b21f2b339b3fc7a14f/mbcd/sac_mbcd.py#L637
If I'm not mistaken, this method should set the rollout length based on `self.rollout_schedule` attribute.
I don't understand why at line `649` we initialize for the first time a new attribute named `self._next_idx`. The attribute is not use anywhere else and so its value is not used. Maybe the line was intended to be `self.replay_buffer._next_idx = len(self.replay_buffer)`?

Thank you in advance for your time

**Comment by LucasAlegre** [comment]
Hi,
You are correct! Thanks for noticing. 
In practice this does not make difference to reproduce our results because we used fixed rollout length of size 1 in our experiments.

**Comment by Valerio-Colombo** [comment]
Ok perfect, thank you for the reply!
