### ISSUE TITLE
Reproducibility issues

### ISSUE THREAD

**Issue by Valerio-Colombo** [LucasAlegre/mbcd#5]
Hi,
I'm trying to get deterministic results once I fix a seed.
At the moment I'm passing the seed argument when execution starts and I fixed the 'n_cpu_tf_sess' variable to 1 as suggested in the code comments.
Doing so, the result is deterministic until policy learning starts. So from timestep 0 to 'learning_starts' timesteps, the result is repeatable. When policy learning starts after the initial exploring phase the results are non longer deterministic.
Is there anything else I need to set up in order to get deterministic results?
Thank you for your time,

Valerio

**Comment by LucasAlegre** [comment]
Hi,
Unfortunately, I am not sure if that is possible (see https://stackoverflow.com/questions/50744565/how-to-handle-non-determinism-when-training-on-a-gpu).
I guess there are some things you can try, perhaps you can find an answer here: https://github.com/hill-a/stable-baselines

Best,
Lucas

**Comment by Valerio-Colombo** [comment]
Hi,
thank you very very much for the responses. I will take a look at the sources you've posted.

Best,
Valerio
